language: cpp

dist: trusty
sudo: false

install: "./tools/emscripten.sh"
before_script: "./tools/emscripten_debug.sh"
script: source tools/emsdk_portable/emsdk_env.sh && make

deploy:
    provider: releases
    api_key:
        secure: "WfFbms3uyASpzcj1ONewaFmCoro3t1G/42Mh4XWtLJX0X7PHZ3M6XNgdOXzPQC8O79qEqQtPjNFcY2CHAVj5G26r461WhLw3SK+24za3XeGQkenaMcRNeaOru3TJMA29cwlS0APtUAU6t6ysDJ99HoPh3wyEi34hj0GEn/E2l9YXuoEwKcdFo5roi+/8sfsfw2e7HrHB3nkWib3NBNsySl+/Fy8b3J1pUdlZQaNAIkKC1E0x3I7kTsBFb1j9u4YanhyiVXlsO0aC2tvThh7iMM10lTdtTcrm4auP9A93Hw8qdAge/5kHK4fQe5iGa/G39IilUfRRajlQ7A6jHqa7hVQoFzwaFERi2LMnT7M5AeruVB7jpCISmCIBbwCPz/jsTzjK41e6sUQVclQzSHzLnj75URQTHSK1ASg1QzBNXs6pA9n6O8Wv+rQbVUYFQAVuS7Ks7VTXiEdzLY7yi1YvUfqtJGR37JEl+xl02mHUco3nFvmbUdupPh5gbXJZW+T3oVREHOtzP6/pEB1DYdAhxvqOw0dC/H3PygAMFjL9UGS8hUIRYqtXWbOZeclX18H0omUUfbrsb39xHxgbaOrR0xsCF8vjENu1VEtZcARuC28vGldBZif4Kv76ooT8Yrr/40EB2ae16Egtg+CAJrs6yL+0g1heW6roMxXGeB6Z20Y="
    file: build/CuraEngine.js
    skip_cleanup: true
    on:
        tags: true
