language: cpp

dist: trusty
sudo: false

install: "./tools/emscripten.sh"
before_script: "./tools/emscripten_debug.sh"
script: source tools/emsdk_portable/emsdk_env.sh && make

cache:
    directories:
        - $HOME/.emscripten_cache/

deploy:
    provider: releases
    api_key:
        secure: "bcOmGg2Dppd+oJhkJfBCbpShLa+tt/JPLy42xMyH3TW5zlsx1fSTS1Mj2L4OZ7teilV+IJZRuIMwrP+2NB3SER0+/ZUz2x7a7YdmbAF0HjIo89KgGjgO8ZW3m7p8utwLqbUg0O7xaRMi3kWB/nziWByfJXkOfR7am4q61/VGNLp8JO5Ydh+Joqtv2MD/NNb22WOeob6OrQxKdvJY0u2BCYBWlGQmLbKwubeE98SlhRvpx4/RKVKcDuqBRhLkk4/maqUCYh3D9sh74QGvL4EK/iesjg6cEddqV0M3z0JodXu5MoBr7BU+jM/Hm9FhOefKsHpuosHNRWLKFFMRndIieP/HwgT1GrdJRE0bc4jabGzKJJOWBmsTieWkOGR+GHHkYULmciVyZVU6XIPACOthNzeDBrArYgfIPV3tYyaoHonR2j+WBAoaJvqPAAk3uW7/oFPgf45+rQZUKMS6b1krbrxdP5h1HjAU7uilXRzTiNcdxyOfCFWEGEe6n2TJiWLG/0CZ3FHLy1yOH5QL8wjPA4t1xB87z6l+R0OQXxMLNRG+AkAWUyL36dvtAc+30iBH0FM6Ff+Kk8fBIyZpgVSn5JTgiIkjK14uej8TqjouywCzw/dAutFQrzAbovYyj3c7PSKqbKME4/fgaYqY5Gt+HHoWDWoMYAEHZf6Yz/mrYGY="
    file: build/CuraEngine.js
    skip_cleanup: true
    on:
        tags: true
